architect:
  - volodya-lombrozo
docker:
  image: lombrozo/rultor-image-java:pr-4
merge:
  script: mvn clean install -Pqulice --errors --batch-mode
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}" "-DprocessPlugins=false"
    git commit -am "${tag}"
    mvn clean install -Pqulice --errors --batch-mode
