name: Performance Regression Check
on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    name: JMH
    runs-on: ubuntu-latest
    steps:
      - name: Run JMH Benchmark Action
        uses: volodya-lombrozo/jmh-benchmark-action@main
        with:
          java-version: "11"
          base-ref: "main"
          benchmark-command: |
            mvn test-compile
            mvn jmh:benchmark -Pbenchmark -Djmh.benchmarks=XnavBenchmark -Djmh.wi=1 -Djmh.i=2 -Djmh.f=1 -Djmh.rf=json -Djmh.rff=benchmark.json
          benchmark-file: "benchmark.json"
        
