name: Performance Regression Check
on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    name: JMH
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR branch
        uses: actions/checkout@v4
        with:
          path: pr
      - name: Check out base branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: base
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Run benchmarks on base branch
        run: |
          cd base
          mvn test-compile
          mvn jmh:benchmark -Pbenchmark -Djmh.benchmarks=XnavBenchmark -Djmh.wi=1 -Djmh.i=2 -Djmh.f=1 -Djmh.rf=json -Djmh.rff=benchmark.json
      - name: Run benchmarks on pr branch
        run: |
          cd pr
          mvn test-compile
          mvn jmh:benchmark -Pbenchmark -Djmh.benchmarks=XnavBenchmark -Djmh.wi=1 -Djmh.i=2 -Djmh.f=1 -Djmh.rf=json -Djmh.rff=benchmark.json
      - name: Debug Benchmark Files
        run: |
          ls -al base/
          ls -al pr/
          cat pr/benchmark.json || echo "PR benchmark file not found"
          cat base/benchmark.json || echo "Base benchmark file not found"
      - name: Compare benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: 'JMH Benchmark Comparison'
          tool: 'jmh'
          output-file-path: pr/benchmark.json
          external-data-json-path: base/benchmark.json
          github-token: ${{ secrets.COMMENTER_TOKEN }}
          comment-on-alert: true
          comment-always: true
          fail-on-alert: true
          save-data-file: false

