name: Post Benchmark Comment
on:
  workflow_run:
    workflows: ["Performance Regression Check"]
    types:
      - completed

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Download Benchmark Comment
        uses: actions/download-artifact@v4
        with:
          name: benchmark-comment

      - name: Read Comment
        id: read_comment
        run: echo "COMMENT_BODY=$(cat benchmark-comment.md)" >> $GITHUB_ENV

      - name: Post Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          message: ${{ env.COMMENT_BODY }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
