name: Post Benchmark Comment
on:
  workflow_run:
    workflows: [ "Performance Regression Check" ]
    types:
      - completed

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Download PR Number
        uses: actions/download-artifact@v4
        with:
          name: pr-number
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Read PR number
        run: echo "PR_NUMBER=$(cat pr-number)" >> $GITHUB_ENV
      - name: Show PR Number
        run: echo "The PR number is ${{ env.PR_NUMBER }}"
      - name: Download Benchmark Comment
        uses: actions/download-artifact@v4
        with:
          name: benchmark-comment
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Post Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          issue: ${{ env.PR_NUMBER }}
          message-path: |
            benchmark-comment.md
          repo-token: ${{ secrets.GITHUB_TOKEN }}
